
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *default
    database: flow7_system_backend_development
  clickhouse:
    adapter: clickhouse
    database: myapp_clickhouse
    host: localhost
    port: 8123
    username: "default"
    password: ""
    timeout: 5000
    migrations_paths: db/migrate_clickhouse


test:
  <<: *default
  database: flow7_system_backend_test


production:
  <<: *default
  database: flow7_system_backend_production
  username: flow7_system_backend
  password: <%= ENV["FLOW7_SYSTEM_BACKEND_DATABASE_PASSWORD"] %>
