development:
  primary:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV.fetch("POSTGRESQL_DATABASE") %>
    username: <%= ENV.fetch("POSTGRESQL_USERNAME") %>
    password: <%= ENV.fetch("POSTGRESQL_PASSWORD") %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: <%= ENV.fetch("POSTGRESQL_HOST") %>
  clickhouse:
    adapter: clickhouse
    database: <%= ENV.fetch("CLICKHOUSE_DATABASE") %>
    host: <%= ENV.fetch("CLICKHOUSE_HOST") %>
    port: 8123
    username: <%= ENV.fetch("CLICKHOUSE_USERNAME") %>
    password: <%#= ENV.fetch("CLICKHOUSE_PASSWORD") { '' } %>
    timeout: 5000
    migrations_paths: db/migrate_clickhouse


test:
  database: flow7_system_backend_test


production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV.fetch("POSTGRESQL_DATABASE") %>
    username: <%= ENV.fetch("POSTGRESQL_USERNAME") %>
    password: <%= ENV.fetch("POSTGRESQL_PASSWORD") %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: <%= ENV.fetch("POSTGRESQL_HOST") %>
  clickhouse:
    adapter: clickhouse
    database: <%= ENV.fetch("CLICKHOUSE_DATABASE") %>
    host: <%= ENV.fetch("CLICKHOUSE_HOST") %>
    port: 8123
    username: <%= ENV.fetch("CLICKHOUSE_USERNAME") %>
    password: <%#= ENV.fetch("CLICKHOUSE_PASSWORD") { '' } %>
    timeout: 5000
    migrations_paths: db/migrate_clickhouse
